<%@ Page Title="APPLY ONLINE" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Apply.aspx.cs" Inherits="Default2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            text-align: left;
            font-size: xx-large;
            color: #000066;
            }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            text-align: center;
        }
        .auto-style4 {
            font-size: x-large;
        }
        .auto-style5 {
            font-size: x-large;
            text-align: center;
        }
    .auto-style6 {
        text-decoration: underline;
    }
    .auto-style7 {
        font-size: x-large;
        color: rgb(0, 0, 153);
    }
    .auto-style8 {
        font-size: x-large;
        color: rgb(51, 51, 153);
    }
    .auto-style9 {
        text-decoration: underline;
        font-size: xx-large;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <div class="auto-style1">
        <table class="auto-style2">
            <tr>
                <td class="auto-style3"><span class="auto-style9">Welcome To Internet Banking</span><br class="auto-style9" />
                    <span class="auto-style9">Apply Online
                    </span>
                    <br class="auto-style6" />
                </td>
            </tr>
        </table>
        <hr />
       <br />
        <span class="auto-style4">This agreement:</span>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            In the last section of this agreement, you will find definitions of some of the words and phrases used in these terms and conditions.</p>
        <h5 class="auto-style4" style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 1em 0px 1em auto; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: 300; font-style: normal; text-rendering: optimizeLegibility; line-height: 1.1; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">1. THE ACCOUNTS ON WHICH YOU MAY USE THE SERVICES</h5>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            1.1 By agreeing to be bound by the terms of this agreement, you agree that the Service will be available on all eligible accounts with us, whether open now or opened in the future, including any joint accounts you hold with others. The Service cannot be used on some types of accounts and we will advise you from time to time as to which accounts are eligible.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            1.2 In order to use the Service, you must be :</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            1.2.1 an account holder with Standard Chartered Bank, India and aged 18 or over; and</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            1.2.2 registered by us to use the Service.</p>
        <h5 class="auto-style4" style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 1em 0px 1em auto; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: 300; font-style: normal; text-rendering: optimizeLegibility; line-height: 1.1; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">2. FOLLOWING OUR USER GUIDANCE</h5>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            2.1 User Guidance on the operation of the Service will be made available to you. User Guidance will cover (among other things) the times when the Service is available, how to access and operate the Service, what things you can and cannot do with the Service, and the time it usually takes to carry out particular types of transactions. You must follow all relevant User Guidance whenever you access and operate the Service.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            2.2 We may inform you from time to time about changes to the way you should access or operate the Service. You must observe all such changes when accessing or operating the Service.</p>
        <h5 class="auto-style4" style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 1em 0px 1em auto; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: 300; font-style: normal; text-rendering: optimizeLegibility; line-height: 1.1; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">3. YOUR RESPONSIBILITIES FOR SECURITY - I/we have read through &amp; hereby confirm having requisite knowledge and experience in using online/electronic mediums of banking.</h5>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.1 To ensure that you alone are able to access and give instructions on your accounts using the Service, you must adopt and at all times maintain the following security procedures.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.2 To enable you to use the Service, we will give you a user identification code and an initial password and you may then choose your own Password for the Service. These are your Security Codes and both will be used to identify you whenever you access the Service. If you are agreeing to the terms of this agreement jointly with others, we will give each of you a unique user identification code and an initial password and each of you may then choose your own individual Password. Both of you will be jointly and severally liable to us for all dues payable to us and/or in case of loss/ damage, whatsoever, caused/suffered to/by us due to use of any or all of the service.</p>
        <h5 class="auto-style4" style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 1em 0px 1em auto; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: 300; font-style: normal; text-rendering: optimizeLegibility; line-height: 1.1; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">Safeguarding your Password and Security Codes</h5>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.3 In connection with your Security Codes:</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.3.1 you should change your Password regularly and may do so if the Service requires you to do so. You should not choose a Password you have used before;:</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.3.2 whenever you choose a Password, you must take care not to choose a number that is likely to be guessed by anyone trying to access the Service pretending to be you. For example, you should avoid your own or a relative&#39;s birthday or any part of your telephone number;:</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.3.3 you must take all reasonable steps to ensure that you safeguard your Security Codes at all times. You must not disclose any details of your Password to anyone else, including to someone who is a joint account holder with you, or to a member of our staff, or to someone giving assistance on a technical helpdesk in connection with the Service;:</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.3.4 you must not record your Security Codes in a way that could make them recognisable by someone else as Security Codes;:</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.3.5 if you discover or suspect that your Password or any part of them are known to someone else, you must immediately change the Password yourself through the Service. If this is not possible, you must notify us immediately by telephoning us on our Phone Banking Centre Numbers (or any other number we may let you have from time to time for this purpose). We will suspend use of the Service until new Security Codes have been set up. Any transaction done prior to such a notification and done within1 working day after giving such notice, shall be entirely at your risk and cost.:</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style7">
            Checking your statements</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.4 If you become aware of any transaction on any of your accounts that has not been validly authorised by you, you must notify us immediately by telephoning us on our Phone Banking Centre Numbers (or any other number we may let you have from time to time for this purpose). For this purpose, you are reminded that you must, as is required of you for all your accounts, check all bank Statements for any unauthorised transactions.</p>
        <h6 style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 2em 0px 0.5em auto; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; font-style: normal; text-rendering: optimizeLegibility; line-height: 1.1; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style8">Other security safeguards</h6>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.5 You must not allow anyone else to operate the Service on your behalf.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.6 You must not leave Your System unattended while you are on-line to the Service. This applies whether Your System is a device you have sourced independently of us or a device provided by us to access the Service in one of our branches. However, the public nature of our branches makes it particularly important that if you access the Service from a device in one of our branches you do not leave that device unattended while on-line and you ensure that you have gone off-line before leaving the branch.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.7 You must not access the Service from any device connected to a local area network (or LAN), such as an office environment, without first making sure that no one else is able to observe or copy your access or obtain access to the Service pretending to be you.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.8 You must comply with any other requirements designed to protect the security of your use of the Service which are set out in the User Guidance or notified by us to you in any other way.</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            3.9 We will not be liable in any manner whatsoever due to unauthorised usage and for all purposes any usage will be construed as a proper and authenticated usage.</p>
        <h5 class="auto-style4" style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 1em 0px 1em auto; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: 300; font-style: normal; text-rendering: optimizeLegibility; line-height: 1.1; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">4. YOUR AUTHORITY TO US TO CARRY OUT INSTRUCTIONS</h5>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            4.1 You agree that the use of the Security Codes agreed between us for the Service is adequate identification of you. We are entitled, but not obliged, to act on instructions (using the Security Codes via the Service) without obtaining any further written or other confirmation from you, even if those instructions are not actually given or authorised by you (except in the circumstances described in section 4.2).</p>
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style4">
            &nbsp;</p>
        <hr />
        <p style="box-sizing: border-box; text-size-adjust: none; -webkit-font-smoothing: antialiased; margin: 0px 0px 17px; padding: 0px; direction: ltr; font-family: &quot;SC Sans Web&quot;, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3em; color: rgb(66, 66, 66); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);" class="auto-style5">
            <asp:Button ID="Button1" runat="server" BorderStyle="Double" CssClass="btn-primary" Text="Agree" PostBackUrl="~/ApplyOnline.aspx" />
&nbsp;&nbsp;
            <asp:Button ID="Button2" runat="server" BorderStyle="Double" CssClass="btn-primary" Text="Disagree" PostBackUrl="~/Apply.aspx" />
        </p>


    </div>



   


</asp:Content>

